// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/layer/service.proto

package layer

import (
	fmt "fmt"
	common "github.com/aquasecurity/trivy/rpc/common"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PutRequest struct {
	LayerId              string                `protobuf:"bytes,1,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	SchemaVersion        int32                 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Os                   *common.OS            `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	PackageInfos         []*common.PackageInfo `protobuf:"bytes,4,rep,name=package_infos,json=packageInfos,proto3" json:"package_infos,omitempty"`
	Applications         []*common.Application `protobuf:"bytes,5,rep,name=applications,proto3" json:"applications,omitempty"`
	OpaqueDirs           []string              `protobuf:"bytes,6,rep,name=opaque_dirs,json=opaqueDirs,proto3" json:"opaque_dirs,omitempty"`
	WhiteoutFiles        []string              `protobuf:"bytes,7,rep,name=whiteout_files,json=whiteoutFiles,proto3" json:"whiteout_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91f12d9b0f6e117e, []int{0}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetLayerId() string {
	if m != nil {
		return m.LayerId
	}
	return ""
}

func (m *PutRequest) GetSchemaVersion() int32 {
	if m != nil {
		return m.SchemaVersion
	}
	return 0
}

func (m *PutRequest) GetOs() *common.OS {
	if m != nil {
		return m.Os
	}
	return nil
}

func (m *PutRequest) GetPackageInfos() []*common.PackageInfo {
	if m != nil {
		return m.PackageInfos
	}
	return nil
}

func (m *PutRequest) GetApplications() []*common.Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

func (m *PutRequest) GetOpaqueDirs() []string {
	if m != nil {
		return m.OpaqueDirs
	}
	return nil
}

func (m *PutRequest) GetWhiteoutFiles() []string {
	if m != nil {
		return m.WhiteoutFiles
	}
	return nil
}

type PutResponse struct {
	Os                   *common.OS `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Eosl                 bool       `protobuf:"varint,2,opt,name=eosl,proto3" json:"eosl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91f12d9b0f6e117e, []int{1}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetOs() *common.OS {
	if m != nil {
		return m.Os
	}
	return nil
}

func (m *PutResponse) GetEosl() bool {
	if m != nil {
		return m.Eosl
	}
	return false
}

type Layers struct {
	LayerIds             []string `protobuf:"bytes,1,rep,name=layer_ids,json=layerIds,proto3" json:"layer_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Layers) Reset()         { *m = Layers{} }
func (m *Layers) String() string { return proto.CompactTextString(m) }
func (*Layers) ProtoMessage()    {}
func (*Layers) Descriptor() ([]byte, []int) {
	return fileDescriptor_91f12d9b0f6e117e, []int{2}
}

func (m *Layers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Layers.Unmarshal(m, b)
}
func (m *Layers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Layers.Marshal(b, m, deterministic)
}
func (m *Layers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Layers.Merge(m, src)
}
func (m *Layers) XXX_Size() int {
	return xxx_messageInfo_Layers.Size(m)
}
func (m *Layers) XXX_DiscardUnknown() {
	xxx_messageInfo_Layers.DiscardUnknown(m)
}

var xxx_messageInfo_Layers proto.InternalMessageInfo

func (m *Layers) GetLayerIds() []string {
	if m != nil {
		return m.LayerIds
	}
	return nil
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "trivy.layer.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "trivy.layer.PutResponse")
	proto.RegisterType((*Layers)(nil), "trivy.layer.Layers")
}

func init() { proto.RegisterFile("rpc/layer/service.proto", fileDescriptor_91f12d9b0f6e117e) }

var fileDescriptor_91f12d9b0f6e117e = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x8b, 0xdb, 0x30,
	0x14, 0xc4, 0xc9, 0xe6, 0x4b, 0xde, 0x94, 0xa2, 0x42, 0xd7, 0x9b, 0x3d, 0xd4, 0x04, 0x16, 0x7c,
	0x92, 0x21, 0x85, 0x85, 0x1e, 0x5a, 0xe8, 0x27, 0x2c, 0xb4, 0x34, 0xb8, 0xd0, 0x43, 0x2f, 0x46,
	0x71, 0x14, 0x47, 0xd4, 0xf6, 0x53, 0xf4, 0xa4, 0x94, 0xf4, 0x8f, 0xf5, 0xef, 0x15, 0x4b, 0x09,
	0xa9, 0x21, 0xf4, 0xe6, 0x19, 0x8d, 0xe7, 0xe9, 0xcd, 0x88, 0xdc, 0x68, 0x55, 0xa4, 0x15, 0x3f,
	0x08, 0x9d, 0xa2, 0xd0, 0x7b, 0x59, 0x08, 0xa6, 0x34, 0x18, 0xa0, 0xa1, 0xd1, 0x72, 0x7f, 0x60,
	0xee, 0x68, 0xf6, 0x50, 0x4a, 0xb3, 0xb5, 0x2b, 0x56, 0x40, 0x9d, 0xf2, 0x9d, 0xe5, 0x28, 0x0a,
	0xab, 0xa5, 0x39, 0xa4, 0x4e, 0x94, 0xb6, 0x1e, 0x05, 0xd4, 0x35, 0x34, 0x5d, 0x93, 0xd9, 0x5d,
	0x09, 0x50, 0x56, 0x22, 0x75, 0x68, 0x65, 0x37, 0xa9, 0xa8, 0x95, 0x39, 0xf8, 0xc3, 0xf9, 0x9f,
	0x1e, 0x21, 0x4b, 0x6b, 0x32, 0xb1, 0xb3, 0x02, 0x0d, 0xbd, 0x25, 0x63, 0x37, 0x2c, 0x97, 0xeb,
	0x28, 0x88, 0x83, 0x64, 0x92, 0x8d, 0x1c, 0x7e, 0x5c, 0xd3, 0x7b, 0xf2, 0x04, 0x8b, 0xad, 0xa8,
	0x79, 0xbe, 0x17, 0x1a, 0x25, 0x34, 0x51, 0x2f, 0x0e, 0x92, 0x41, 0x36, 0xf5, 0xec, 0x77, 0x4f,
	0xd2, 0x98, 0xf4, 0x00, 0xa3, 0x7e, 0x1c, 0x24, 0xe1, 0xe2, 0x29, 0xf3, 0xf7, 0xf7, 0xd7, 0x62,
	0x5f, 0xbf, 0x65, 0x3d, 0x40, 0xfa, 0x86, 0x4c, 0x15, 0x2f, 0x7e, 0xf2, 0x52, 0xe4, 0xb2, 0xd9,
	0x00, 0x46, 0x57, 0x71, 0x3f, 0x09, 0x17, 0xb7, 0x5d, 0xf1, 0xd2, 0x4b, 0x1e, 0x9b, 0x0d, 0x64,
	0xd7, 0xea, 0x0c, 0x90, 0xbe, 0x26, 0xd7, 0x5c, 0xa9, 0x4a, 0x16, 0xdc, 0x48, 0x68, 0x30, 0x1a,
	0x5c, 0xfa, 0xfd, 0xed, 0x59, 0x91, 0x75, 0xe4, 0xf4, 0x05, 0x09, 0x41, 0xf1, 0x9d, 0x15, 0xf9,
	0x5a, 0x6a, 0x8c, 0x86, 0x71, 0x3f, 0x99, 0x64, 0xc4, 0x53, 0x1f, 0xa4, 0xc6, 0x76, 0xd1, 0x5f,
	0x5b, 0x69, 0x04, 0x58, 0x93, 0x6f, 0x64, 0x25, 0x30, 0x1a, 0x39, 0xcd, 0xf4, 0xc4, 0x7e, 0x6a,
	0xc9, 0xf9, 0x7b, 0x12, 0xba, 0xe0, 0x50, 0x41, 0x83, 0xe2, 0xb8, 0x77, 0xf0, 0x9f, 0xbd, 0x29,
	0xb9, 0x12, 0x80, 0x95, 0x8b, 0x6d, 0x9c, 0xb9, 0xef, 0xf9, 0x3d, 0x19, 0x7e, 0x6e, 0xf3, 0x45,
	0x7a, 0x47, 0x26, 0xa7, 0xe4, 0x5b, 0x9b, 0x76, 0xe0, 0xf8, 0x18, 0x3d, 0x2e, 0x7e, 0x93, 0x81,
	0x93, 0xd1, 0x07, 0xd2, 0x5f, 0x5a, 0x43, 0x6f, 0xd8, 0x3f, 0x0f, 0x83, 0x9d, 0xfb, 0x9b, 0x3d,
	0x67, 0xbe, 0x6c, 0x76, 0x2a, 0x9b, 0x7d, 0x6c, 0xcb, 0xa6, 0xaf, 0xc8, 0xf4, 0x8b, 0x44, 0x94,
	0x4d, 0x79, 0x1c, 0xf7, 0xac, 0xe3, 0xe0, 0xc9, 0xd9, 0x25, 0xf2, 0xdd, 0xe8, 0xc7, 0xc0, 0xe1,
	0xd5, 0xd0, 0x79, 0xbe, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x56, 0x5b, 0x98, 0xa5, 0xae, 0x02,
	0x00, 0x00,
}
