// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/scanner/service.proto

package scanner

import (
	fmt "fmt"
	common "github.com/aquasecurity/trivy/rpc/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScanRequest struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	ImageId              string   `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	LayerIds             []string `protobuf:"bytes,3,rep,name=layer_ids,json=layerIds,proto3" json:"layer_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60d0e837512b18d4, []int{0}
}

func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ScanRequest) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *ScanRequest) GetLayerIds() []string {
	if m != nil {
		return m.LayerIds
	}
	return nil
}

type ScanResponse struct {
	Os                   *common.OS `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Eosl                 bool       `protobuf:"varint,2,opt,name=eosl,proto3" json:"eosl,omitempty"`
	Results              []*Result  `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60d0e837512b18d4, []int{1}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetOs() *common.OS {
	if m != nil {
		return m.Os
	}
	return nil
}

func (m *ScanResponse) GetEosl() bool {
	if m != nil {
		return m.Eosl
	}
	return false
}

func (m *ScanResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

// Result is the same as github.com/aquasecurity/trivy/pkg/report.Result
type Result struct {
	Target               string                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Vulnerabilities      []*common.Vulnerability `protobuf:"bytes,2,rep,name=vulnerabilities,proto3" json:"vulnerabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_60d0e837512b18d4, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Result) GetVulnerabilities() []*common.Vulnerability {
	if m != nil {
		return m.Vulnerabilities
	}
	return nil
}

func init() {
	proto.RegisterType((*ScanRequest)(nil), "trivy.scanner.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "trivy.scanner.ScanResponse")
	proto.RegisterType((*Result)(nil), "trivy.scanner.Result")
}

func init() { proto.RegisterFile("rpc/scanner/service.proto", fileDescriptor_60d0e837512b18d4) }

var fileDescriptor_60d0e837512b18d4 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x41, 0x6b, 0x2a, 0x31,
	0x10, 0xc6, 0x55, 0x5c, 0x77, 0x7c, 0x8f, 0xf7, 0x08, 0xbc, 0xc7, 0xaa, 0x17, 0xf1, 0xe4, 0x29,
	0x0b, 0x16, 0x7a, 0x2d, 0x14, 0x7a, 0xb0, 0x97, 0x42, 0x84, 0x1e, 0x0a, 0x45, 0x62, 0x76, 0xd8,
	0x06, 0x76, 0x37, 0x9a, 0x49, 0x84, 0xfd, 0xf7, 0xc5, 0xc4, 0x82, 0x4a, 0x7b, 0x9b, 0x99, 0xef,
	0xcb, 0x37, 0xdf, 0x37, 0x81, 0x89, 0xdd, 0xab, 0x82, 0x94, 0x6c, 0x5b, 0xb4, 0x05, 0xa1, 0x3d,
	0x6a, 0x85, 0x7c, 0x6f, 0x8d, 0x33, 0xec, 0xb7, 0xb3, 0xfa, 0xd8, 0xf1, 0x33, 0x38, 0xbd, 0xaf,
	0xb4, 0xfb, 0xf0, 0x3b, 0xae, 0x4c, 0x53, 0xc8, 0x83, 0x97, 0x84, 0xca, 0x5b, 0xed, 0xba, 0x22,
	0xd0, 0x8a, 0x93, 0x8e, 0x32, 0x4d, 0x63, 0xda, 0x6b, 0x99, 0xc5, 0x3b, 0x8c, 0x37, 0x4a, 0xb6,
	0x02, 0x0f, 0x1e, 0xc9, 0xb1, 0xff, 0x30, 0x74, 0xd2, 0x56, 0xe8, 0xf2, 0xde, 0xbc, 0xb7, 0xcc,
	0xc4, 0xb9, 0x63, 0x13, 0x18, 0xe9, 0x46, 0x56, 0xb8, 0xd5, 0x65, 0x9e, 0x04, 0x24, 0x0d, 0xfd,
	0xba, 0x64, 0x33, 0xc8, 0x6a, 0xd9, 0xa1, 0xdd, 0xea, 0x92, 0xf2, 0xfe, 0xbc, 0xbf, 0xcc, 0xc4,
	0x28, 0x0c, 0xd6, 0x25, 0x2d, 0x3c, 0xfc, 0x8a, 0xf2, 0xb4, 0x37, 0x2d, 0x21, 0x9b, 0x43, 0x62,
	0x28, 0x68, 0x8f, 0x57, 0x7f, 0x79, 0x8c, 0x10, 0x7d, 0xf1, 0x97, 0x8d, 0x48, 0x0c, 0x31, 0x06,
	0x03, 0x34, 0x54, 0x87, 0x2d, 0x23, 0x11, 0x6a, 0x56, 0x40, 0x6a, 0x91, 0x7c, 0xed, 0xe2, 0x82,
	0xf1, 0xea, 0x1f, 0xbf, 0x4a, 0xcf, 0x45, 0x40, 0xc5, 0x17, 0x6b, 0x51, 0xc1, 0x30, 0x8e, 0x7e,
	0x0c, 0xf4, 0x04, 0x7f, 0x8e, 0xbe, 0x6e, 0xd1, 0xca, 0x9d, 0xae, 0xb5, 0xd3, 0x48, 0x79, 0x12,
	0xa4, 0x67, 0xd7, 0xae, 0x5e, 0x2f, 0x48, 0x9d, 0xb8, 0x7d, 0xb3, 0x7a, 0x86, 0x74, 0x13, 0x3d,
	0xb0, 0x07, 0x18, 0x9c, 0x4a, 0x36, 0xbd, 0xf1, 0x76, 0x71, 0xde, 0xe9, 0xec, 0x5b, 0x2c, 0xde,
	0xe6, 0x31, 0x7b, 0x4b, 0xcf, 0xf3, 0xdd, 0x30, 0x7c, 0xce, 0xdd, 0x67, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x43, 0xb9, 0x34, 0x56, 0x00, 0x02, 0x00, 0x00,
}
